create database AnclaSystem;
use AnclaSystem;

CREATE TABLE PRODUCTOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
PRECIO DECIMAL(10,2) NOT NULL,
DESCONTINUADO BOOLEAN NOT NULL,
CHECK (PRECIO > 0)
);

CREATE TABLE INVENTARIO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
UNIDAD VARCHAR(12) NOT NULL,
STOCK INT NOT NULL,
DESCONTINUADO BOOLEAN NOT NULL,
CHECK(STOCK >=0) 
);

CREATE TABLE DETALLE_PRODUCTOS(
ID_PROD INT NOT NULL,
ID_INV INT NOT NULL,
PRIMARY KEY(ID_PROD,ID_INV),
CANTIDAD INT NOT NULL,
CONSTRAINT FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID),
CONSTRAINT FOREIGN KEY (ID_INV) REFERENCES INVENTARIO(ID),
CHECK(CANTIDAD>0));

CREATE TABLE PROVEEDORES(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_EMPRESA VARCHAR(35) NOT NULL,
NOMBRE_CONTACTO VARCHAR(35) NOT NULL,
TELEFONO VARCHAR(15) NOT NULL,
CORREO VARCHAR(30) NOT NULL,
DIRECCION VARCHAR(40) NOT NULL
);

CREATE TABLE USUARIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
NOMBRE_USUARIO VARCHAR(15) NOT NULL UNIQUE,
CONTRASENA VARCHAR(15) NOT NULL,
ES_ADMIN BOOLEAN NOT NULL,
ACTIVO BOOLEAN NOT NULL
);

CREATE TABLE VENTAS(
ID INT AUTO_INCREMENT PRIMARY KEY,
TOTAL DECIMAL(10,2) NOT NULL,
FECHA DATETIME NOT NULL,
ID_CAJERO INT NOT NULL,
CONSTRAINT FOREIGN KEY (ID_CAJERO) REFERENCES USUARIOS(ID),
CHECK(TOTAL>0)
);

CREATE TABLE DETALLE_VENTAS(
ID_PROD INT NOT NULL,
ID_VENT INT NOT NULL,
PRIMARY KEY(ID_PROD, ID_VENT),
CANTIDAD INT NOT NULL,
PRECIO_VENTA DECIMAL(10,2) NOT NULL,
CONSTRAINT FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID),
CONSTRAINT FOREIGN KEY (ID_VENT) REFERENCES VENTAS(ID)
);
